<a href="https://colab.research.google.com/github/masoom-alam/Basics_Python/blob/main/BasicsPython.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
ar1=np.array(5)
ar1

array(5)

In [7]:
ar2 = np.array([[1,2,3,5,6],[3,5,6,7,8]])

In [8]:
ar2

array([[1, 2, 3, 5, 6],
       [3, 5, 6, 7, 8]])

In [9]:
ar3=np.array([[[1,2],[3,5]],[[1,2],[4,7]]])

In [10]:
ar3

array([[[1, 2],
        [3, 5]],

       [[1, 2],
        [4, 7]]])

In [12]:
ar1=np.array([1,2,3,4,5])
ar1.ndim

1

In [13]:
ar4=np.array([[[1,3,4,5,6]]])
ar4.ndim

3

In [20]:
ar4= np.array([1,2,3,4,5],ndmin=4)
ar4.ndim

4

In [21]:
ar3.ndim


3

In [22]:
ar4.shape

(1, 1, 1, 5)

In [23]:
ar4.dtype

dtype('int64')

In [24]:
ar3.itemsize

8

In [25]:
ar3.nbytes

64

In [27]:
ar5=np.array([1.2,2.2,4.4])
ar5.dtype

dtype('float64')

In [30]:
ar=np.zeros((3,4,5))

In [31]:
ar

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [34]:
ar=np.ones(3)
ar


array([1., 1., 1.])

In [36]:
ar3=np.empty((1,2))
ar3

array([[-5.73021895e-300,  6.75868821e-310]])

In [37]:
ar5=np.eye(3)
ar5

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [38]:
ar1=np.diag([2,3,4])
ar1

array([[2, 0, 0],
       [0, 3, 0],
       [0, 0, 4]])

In [39]:
ar4=np.linspace(0,10,5)
ar4

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [40]:
a=np.zeros(3)
a

array([0., 0., 0.])